### PR TITLE
Scrollable task spinner

### LINKED ISSUE #818: Add a scroll ability on task loader
Limit task loader height so it fits inside the terminal and keep space for a few log lines.

Add a scroll feature using keyboard arrow keys, and counters of running/done/failed tasks.
Example of awaited screen:
```
[wks-b#build] Running ...
[wks-c#build] Running ...
[wks-a#build] Success !
-[more up]-----------------
⠼ Run build in wks-b
  ⠼ yarn exec tsc
-[more down]---------------
⠼ 2 running, 1 done
```
Dash lines should appear only if some tasks are hidden.

Ensure height is not limited in CI.

### PR DESCRIPTION
**Pull request by Jujulego**
Closes #818

### CODE REVIEW

File: src/ui/task-tree-stats.tsx [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+      done: task.status === 'done' ? old.done + task.weight : old.done,
+      failed: task.status === 'failed' ? old.failed + task.weight : old.failed,
+    }));
+  }), [manager]);
+
+  // Render
+  return (
+    <Text>
+      { (stats.running !== 0) && (
+        <><Spinner type={'sand' as 'dots'} /> <Text bold>{ stats.running }</Text> running</>
```
Comment (julien-capellari) [inline src/ui/task-tree-stats.tsx]: Remove cast when https://github.com/sindresorhus/cli-spinners/pull/69 is published
